// Code generated by mockery v2.53.3. DO NOT EDIT.

package loglevel

import (
	context "context"

	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// MockDoguDescriptorGetter is an autogenerated mock type for the DoguDescriptorGetter type
type MockDoguDescriptorGetter struct {
	mock.Mock
}

type MockDoguDescriptorGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguDescriptorGetter) EXPECT() *MockDoguDescriptorGetter_Expecter {
	return &MockDoguDescriptorGetter_Expecter{mock: &_m.Mock}
}

// GetCurrent provides a mock function with given fields: ctx, simpleDoguName
func (_m *MockDoguDescriptorGetter) GetCurrent(ctx context.Context, simpleDoguName string) (*core.Dogu, error) {
	ret := _m.Called(ctx, simpleDoguName)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrent")
	}

	var r0 *core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*core.Dogu, error)); ok {
		return rf(ctx, simpleDoguName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *core.Dogu); ok {
		r0 = rf(ctx, simpleDoguName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, simpleDoguName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoguDescriptorGetter_GetCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrent'
type MockDoguDescriptorGetter_GetCurrent_Call struct {
	*mock.Call
}

// GetCurrent is a helper method to define mock.On call
//   - ctx context.Context
//   - simpleDoguName string
func (_e *MockDoguDescriptorGetter_Expecter) GetCurrent(ctx interface{}, simpleDoguName interface{}) *MockDoguDescriptorGetter_GetCurrent_Call {
	return &MockDoguDescriptorGetter_GetCurrent_Call{Call: _e.mock.On("GetCurrent", ctx, simpleDoguName)}
}

func (_c *MockDoguDescriptorGetter_GetCurrent_Call) Run(run func(ctx context.Context, simpleDoguName string)) *MockDoguDescriptorGetter_GetCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDoguDescriptorGetter_GetCurrent_Call) Return(_a0 *core.Dogu, _a1 error) *MockDoguDescriptorGetter_GetCurrent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoguDescriptorGetter_GetCurrent_Call) RunAndReturn(run func(context.Context, string) (*core.Dogu, error)) *MockDoguDescriptorGetter_GetCurrent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguDescriptorGetter creates a new instance of MockDoguDescriptorGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguDescriptorGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguDescriptorGetter {
	mock := &MockDoguDescriptorGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
