// Code generated by mockery v2.53.3. DO NOT EDIT.

package loglevel

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDoguRestarter is an autogenerated mock type for the DoguRestarter type
type MockDoguRestarter struct {
	mock.Mock
}

type MockDoguRestarter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoguRestarter) EXPECT() *MockDoguRestarter_Expecter {
	return &MockDoguRestarter_Expecter{mock: &_m.Mock}
}

// Restart provides a mock function with given fields: ctx, doguName
func (_m *MockDoguRestarter) Restart(ctx context.Context, doguName string) error {
	ret := _m.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for Restart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, doguName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDoguRestarter_Restart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restart'
type MockDoguRestarter_Restart_Call struct {
	*mock.Call
}

// Restart is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName string
func (_e *MockDoguRestarter_Expecter) Restart(ctx interface{}, doguName interface{}) *MockDoguRestarter_Restart_Call {
	return &MockDoguRestarter_Restart_Call{Call: _e.mock.On("Restart", ctx, doguName)}
}

func (_c *MockDoguRestarter_Restart_Call) Run(run func(ctx context.Context, doguName string)) *MockDoguRestarter_Restart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDoguRestarter_Restart_Call) Return(_a0 error) *MockDoguRestarter_Restart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoguRestarter_Restart_Call) RunAndReturn(run func(context.Context, string) error) *MockDoguRestarter_Restart_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoguRestarter creates a new instance of MockDoguRestarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoguRestarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoguRestarter {
	mock := &MockDoguRestarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
