apiVersion: v1
values:
  images:
    componentOperator: cloudogu/debug-mode-operator:0.0.0
patches:
  values.yaml:
    additionalImages:
    manager:
      image:
        registry: "{{ registryFrom .images.componentOperator }}"
        repository: "{{ repositoryFrom .images.componentOperator }}"
        tag: "{{ tagFrom .images.componentOperator }}"