# The k8s-component-operator must be able to install all components using Helm.
# Since those components contain cluster-scoped resources (like CRDs, ClusterRoles, ClusterRoleBindings, ...)
# the k8s-component-operator also needs permissions to manage the resources.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-debug-mode-operator.name" . }}-cluster-role
  labels:
   {{- include "k8s-debug-mode-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
