apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-debug-mode-operator.name" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "k8s-debug-mode-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
    {{- include "k8s-debug-mode-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        control-plane: controller-manager
      {{- include "k8s-debug-mode-operator.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
        name: manager
        env:
        - name: STAGE
          value: {{ quote .Values.controllerManager.manager.env.stage | default "production" }}
        - name: LOG_LEVEL
          value: {{ quote .Values.controllerManager.manager.env.logLevel | default "info"}}
        image: "{{ .Values.controllerManager.manager.image.registry }}/{{ .Values.controllerManager.manager.image.repository }}:{{ .Values.controllerManager.manager.image.tag }}"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
          {{- toYaml .Values.controllerManager.manager.resourceLimits | nindent 14 }}
          requests:
          {{- toYaml .Values.controllerManager.manager.resourceRequests | nindent 14 }}
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: {{ include "k8s-debug-mode-operator.name" . }}-controller-manager
      terminationGracePeriodSeconds: 10
